### ISSUE TITLE
Nondistinct user agent

### ISSUE THREAD

**Issue by Ironholds** [ritschwumm/scmw#1]
The Wikimedia/MediaWiki API etiquette guidelines require at least either a valid contact address, or a project URL.

**Comment by ritschwumm** [comment]
where do i find those? and what do you mean by "nondistinct"?

**Comment by Ironholds** [comment]
"scmw/[version number]" doesn't tell us who to contact if something goes wrong, or where to go if there's a bug.

https://www.mediawiki.org/wiki/API:Etiquette#User-Agent_header "Use a descriptive User-Agent header that includes your application's name and potentially your email address if appropriate...this ensures that if a problem does arise it is easy to track down where it originates."

So, strictly-speaking, you don't _need_ to, I guess. But [it's probably advisable](https://www.google.com/search?client=ubuntu&channel=fs&q=scmw&ie=utf-8&oe=utf-8)
